In [1]:
import numpy as np
import matplotlib.pyplot as plt
from fancyIndex4py import getResult
import importlib 
from numba import njit,jit
from scipy.sparse import csr_matrix, csc_matrix


In [ ]:
data = np.load("data_1M.bin.npy").view(np.uint16).reshape(-1,511)

In [8]:
target = np.arange(2**16).reshape(-1,1).astype(np.int32)

In [4]:
index = np.random.randint(0, data.shape[1], (70000,16),dtype=np.int32)

In [14]:
tmp = getResult(data, index[:70000],target)

In [17]:
tmp.shape

(100, 1024)

In [11]:
mask = 2**np.arange(16)
# mask = 2**np.concatenate([np.arange(8,16),np.arange(8)])

In [11]:
(np.bincount(np.bitwise_and(data[:1000000,index[0]],mask).sum(axis=1),minlength=2**16)-tmp[0]).sum()

0

In [28]:
np.abs(np.bincount(np.bitwise_and(data[:1000000,index[0]],mask).sum(axis=1),minlength=2**16)[-100:-50]-tmp[0][-100:-50]).sum()

134881

In [9]:
for n in range(10):
    print(np.abs(np.bitwise_and(data[:1000000,index[n]],mask).sum(axis=1)-tmp[n]).sum())

ValueError: operands could not be broadcast together with shapes (1000000,) (65536,) 

In [30]:
mask

array([  256,   512,  1024,  2048,  4096,  8192, 16384, 32768,     1,
           2,     4,     8,    16,    32,    64,   128])

In [25]:
tmp[0]

array([      1963,        199,        654, ...,      31033, 1952463648,
            31033], dtype=int32)

In [35]:
np.bincount(np.bitwise_and(data[:,index[0]],mask).sum(axis=1),minlength=2**16)

array([1963,  199,  654, ...,    0,    0,    0])

In [12]:
[np.abs(np.bincount(np.bitwise_and(data[:,index[_]],mask).sum(axis=1),minlength=2**16) - tmp[_]).sum() for _ in range(10)] 

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [7]:
np.bincount(tmp)

array([6369, 4677, 2500, ...,    0,    0,    1])

In [9]:
mask = 2**np.arange(16)
np.bincount(np.bitwise_and(data[:,index[1]],mask).sum(axis=1))

array([1424, 1050,  691, ...,    0,    0,    1])

In [9]:
np.abs(np.bincount(tmp) - np.bincount(np.bitwise_and(data[:,index[0]],mask).sum(axis=1))).max()

0

In [34]:
np.array([(data[0][_]*2**np.concatenate([np.arange(8,0,-1)-1,np.arange(15,7,-1)])).sum() for _ in range(100)])

array([    0,     0,     0,     0,     0, 16384,     0,     0,     0,
           0,     0,     0,     0,     0,  2048,     0,    10,  1024,
           1,     0,    64,   128, 16386,     0,    16,     0,    64,
           0, 32768,  8256,  6275,  2320,     0,   258,  1536,     0,
        8208,     0,     2,     0,  2180, 32769,   128,   100,     0,
        4736,   256,   128,    75,    20, 16384,     1,     8, 32769,
         144,  4097, 32768,    24,    32,     0,     0,   288,    16,
       32785,     0, 35345,  8352,    10,   804,    20,    11,    68,
        8906, 19392, 32817, 32784,     0,  2568, 40977,  1028,   514,
       32819,     1, 32772, 41477,  4096, 32832, 24577, 33168,    22,
       16498, 49202, 33028, 17729,  8272,  2309,  8272, 21024,  8193,
       32770])

In [10]:
data[0]

array([    0,     0,     0,     0,     0, 16384,     0,     0,     0,
           0,     0,     0,     0,     0,  2048,     0,    10,  1024,
           1,     0,    64,   128, 16386,     0,    16,     0,    64,
           0, 32768,  8256,  6275,  2320,     0,   258,  1536,     0,
        8208,     0,     2,     0,  2180, 32769,   128,   100,     0,
        4736,   256,   128,    75,    20, 16384,     1,     8, 32769,
         144,  4097, 32768,    24,    32,     0,     0,   288,    16,
       32785,     0, 35345,  8352,    10,   804,    20,    11,    68,
        8906, 19392, 32817, 32784,     0,  2568, 40977,  1028,   514,
       32819,     1, 32772, 41477,  4096, 32832, 24577, 33168,    22,
       16498, 49202, 33028, 17729,  8272,  2309,  8272, 21024,  8193,
       32770, 34238,    32,   320,     7,  2080, 33107,   138, 43430,
        5838, 41090, 33456,    12,  8451,  8192,   137,  8389,   580,
       16416,  4704, 37376, 32792, 14710,    67,    45,  2569, 49169,
          22, 10821,

In [3]:
data.shape

(1000000, 511)

In [ ]:
data = np.load("/home/g/data/GBS/GBS4/0120/power1/data_1M.bin.npy").view(np.uint16).reshape(-1,511)
index = np.random.randint(0, data.shape[1], (70000,16),dtype=np.int32)
mask = 2**np.arange(16)
np.bincount(np.bitwise_and(data[:,index[0]],mask).sum(axis=1))

In [4]:
index.shape

(70000, 16)

In [91]:
data.max()

65535

In [6]:
tmp.max()

1

In [8]:
tmp.sum()

113187

In [63]:
mask

array([    1,     2,     4,     8,    16,    32,    64,   128,   256,
         512,  1024,  2048,  4096,  8192, 16384, 32768])

In [70]:
%%timeit
np.bincount(np.bitwise_and(data[:,index[0]],mask).sum(axis=1))

92.2 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [76]:
%%timeit
t = np.zeros_like(index[0],dtype=np.int32)
for i in range(70000):
    t+=index[i]

29 ms ± 322 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
choice = np.zeros((len(data),511),dtype=np.int32)
for _ in range(16):
    choice[:,index[0,_]] += 2**_
tmp = np.bitwise_and(data,choice).sum(axis=1)

In [50]:
choice[choice>0].shape

(15000000,)

In [68]:
np.bincount(tmp)

array([1608, 1133,  910, ...,    0,    0,    1])

In [33]:
np.sort(choice[choice>0])

array([    1,     2,     4,     8,    32,    64,   128,   256,   512,
        1024,  2048,  4096,  8192, 16384, 32768], dtype=int32)

In [27]:
len(set(index[1]))

15

In [29]:
(choice>0).sum()

16

In [7]:
index

array([[287, 164, 463, ..., 216, 297, 415],
       [390, 262, 149, ...,  20, 160,  93],
       [203, 415,  92, ..., 482,  25, 279],
       ...,
       [110, 448,  81, ..., 350, 308, 219],
       [387, 209, 376, ..., 176, 433, 240],
       [475, 382, 363, ...,  26, 130, 140]], dtype=int32)

In [12]:
%%time
tmp = data[:,index].transpose(1, 0, 2)

CPU times: user 7.78 s, sys: 167 ms, total: 7.95 s
Wall time: 7.95 s


In [4]:
# %%timeit
tmp2 = np.take(data,index,axis=1).transpose(1, 0, 2)

In [5]:
tmp2.shape

(100, 1000000, 16)

In [6]:
@jit(nopython=True, fastmath=True)
def fancyIndex(x, idx):
    res = np.empty((len(idx),len(x),idx.shape[1]), dtype=x.dtype)
    for i in range(len(idx)):
        res[i] = x[:,idx[i]]
    return res

In [13]:
%%time
tmp3 = fancyIndex(data,index)

CPU times: user 8.58 s, sys: 794 ms, total: 9.38 s
Wall time: 9.32 s


In [9]:
tmp3.shape

(100, 1000000, 16)

In [10]:
np.abs(tmp2-tmp3).sum()

0

In [32]:
tmp2.shape

(100, 200000, 16)

In [5]:
tmp.shape

(100, 200000, 16)

In [9]:
tmp2 = fancyIndex4py.fancyIndex(data[:1000000],index)

In [8]:
np.abs(tmp2.reshape(100, 200000, 16)-tmp).sum()

0

In [9]:
tmp[0,0]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0], dtype=uint8)